FROM python:3.12-slim

WORKDIR /dashboard

COPY requirements.dashboard.txt .
RUN pip install --no-cache-dir -r requirements.dashboard.txt

COPY dashboard/ .

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]
